---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-kubernetes-resources
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 4bd9e926-a311-4f6e-bbaa-a55bf6c3c163
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-ocp.sh"
        post_validation: "tests/scripts/post-validation-destroy-ocp.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
